spring.application.name=baithak
server.port=7001
redis.url=redis://localhost:6379
spring.datasource.url=jdbc:postgresql://localhost:5432/baithak
spring.datasource.username=hemantsinghsisodiya
spring.datasource.password=Keychain@123
spring.datasource.driver-class-name=org.postgresql.Driver